### PR TITLE
WIP on issue 95-create-new-project-layers-in-databases

### PR DESCRIPTION
**Pull request by Sandeep-1-Kumar**
Extract the necessary information from the request payload, including the label, creator, and items (annotation pages).
Use the AnnotationCollectionFactory function to create the annotation collection based on the extracted information.
Iterate over the items in the payload and use the AnnotationPageFactory function to create the annotation pages associated with the annotation collection.
Save the newly created annotation collection and pages to the "tiny" database.
Update the project's layers array with the ID of the newly created annotation collection.

### CODE REVIEW

**Review by thehabes — CHANGES_REQUESTED** [review]
The tests within your scope are failing.  Please make sure the /project tests pass before asking for a review.  These tests are passing on `development` and so the failures are due to your code changes.

Found by running `npm run allTests` before looking at code.

image

**Comment by Sandeep-1-Kumar** [comment]
The postman scrn shot.
image

**Review by thehabes — CHANGES_REQUESTED** [review]
You did not fix the error mentioned in the previous review.   I also still do not see tests for the new endpoint(s) you registered either.  All endpoints that intend to be merged with `development` must have some kind of useful test(s).  
> Your PR has been switched back to 'Draft' because you have not written these tests.

image

**Comment by Sandeep-1-Kumar** [comment]
Please add /addLayer endpoint the URL
In the issue it is mentioned to route URL : http://localhost:3009/project/abcdefg111222333/addLayer

**Comment by thehabes** [comment]
@Sandeep-1-Kumar 
The ability to retrieve a project by id is within your scope.  There must exist a project that you access to make this change.  A successful result of `/addLayer` means when I GET the project (by id) that you added the layer to, I see that layer.  I cannot complete the end to end demo unless I am able to GET a project by its id.

**Comment by thehabes** [comment]
Ahh I see it tricked you because that project did not have the "layers" property to begin with.
I made another one and did the test again, and that one got your layer.
{
  "_id": "66269be6b9a635de8efb4bef",
  "@type": "Project",
  "name": "Test Project -- Updated",
  "layers": [
    "https://store.rerum.io/v1/id/bzy0DprpgneWObJy"
  ]
}
However, that URI is not what I expect.  The function had created a layer with the id "https://devstore.rerum.io/v1/id/6626b0ade8afc731e3b58db3" which I what should be there.

**Comment by Sandeep-1-Kumar** [comment]
> You did not fix the error mentioned in the previous review. I also still do not see tests for the new endpoint(s) you registered either. All endpoints that intend to be merged with `development` must have some kind of useful test(s).
> 
> > Your PR has been switched back to 'Draft' because you have not written these tests.
> 
> image

GET is updated and working : http://localhost:3009/project/6626a0a3fb14b79f3293e41e
image

**Comment by Sandeep-1-Kumar** [comment]
All my test cases nare passing because i have this project in my local Mongo DB : "abcdefg111222333"

**Comment by Sandeep-1-Kumar** [comment]
I had fixed this @thehabes and waiting on your review, Thank you.

**Review by thehabes — CHANGES_REQUESTED** [review]
Tests pass and the app does start up.  However, I've run into unexpected behavior.  

http://localhost:3009/project/66269be6b9a635de8efb4bef/addLayer
image

This call succeeds with a 201 and says it create this collection
https://devstore.rerum.io/v1/id/3OOsk4LJGsCE4B9V

That URI does not resolve to anything (404).  That means you did not save the Collection to the database, and now this project will have a Layer that is 404.

I went into the database to see what layer was added to this project.  However, the `layers` array is empty and so this project did not receive a layer.

image

This does not meet the minimal functional requirements.  You need to generate and save an Annotation Collection, then take the URI from that succeeding and add it to the TPEN Project's `layers` array.

You should write tests for those functional requirements.  Your tests should not have passed because /addLayer was not functional.  I see you still have not written tests for the /addLayer endpoint.  This PR is a Draft until you have written tests.

**Comment by thehabes** [comment]
You do have some tests!  They just aren't quite right, and you are missing the /exists tests.  Make sure you meet the minimum functional requirements and test them before taking this out of Draft.

**Comment by cubap** [comment]
> Tests pass and the app does start up. However, I've run into unexpected behavior.
> This call succeeds with a 201 and says it create this collection https://devstore.rerum.io/v1/id/3OOsk4LJGsCE4B9V

This is bizarre. That is not even a hexstring.

**Pull request closed without merging**
